complexity:
  LongParameterList:
    ignoreDefaultParameters: true
  TooManyFunctions:
    ignoreOverridden: true
naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'
