name: Pull Request Build

on:
  pull_request:

jobs:
  validateGradle:
    uses: slav-dev/.workflows/gradle-validate-wrapper.yml@main
  runChecks:
    needs: validateGradle
    uses: slav-dev/.workflows/android-check.yml@main
  assembleRelease:
    needs: validateGradle
    uses: slav-dev/.workflows/android-assemble.yml@main
    with:
      variant: Release
