name: Push Build

on:
  push:
    branches: [ main ]

jobs:
  validateGradle:
    name: Validate Gradle Wrapper
    uses: slav-dev/.workflows/.github/workflows/gradle-validate-wrapper.yml@main
  publishSnapshot:
    name: Publish Snapshot
    secrets: inherit
    needs: validateGradle
    uses: slav-dev/.workflows/.github/workflows/gradle-snapshot.yml@main
  draftRelease:
    name: Draft Release
    permissions:
      contents: write
      discussions: write
    needs: validateGradle
    uses: slav-dev/.workflows/.github/workflows/gradle-draft-release.yml@main
    with:
      discussion_category_name: Announcements
